
CREATE FUNCTION IF NOT EXISTS INTERNAL.GET_CREDIT_COST()
    RETURNS NUMBER AS
    $$2.0$$;

CREATE FUNCTION IF NOT EXISTS INTERNAL.GET_SERVERLESS_CREDIT_COST()
    RETURNS NUMBER AS
    $$3.0$$;

CREATE FUNCTION IF NOT EXISTS INTERNAL.GET_STORAGE_COST()
    RETURNS NUMBER AS
    $$40.0$$;


CREATE OR REPLACE FUNCTION INTERNAL.IS_SERVERLESS_WAREHOUSE(warehouse number)
    RETURNS BOOLEAN AS
    $$
    warehouse > 700000
    $$;

-- Variant of IS_SERVERLESS_WAREHOUSE(number) for information_schema.query_history which
-- does not contain the WAREHOUSE_ID NUMBER column.
CREATE OR REPLACE FUNCTION INTERNAL.IS_SERVERLESS_WAREHOUSE(warehouse_name string)
    RETURNS BOOLEAN AS
    $$
    startswith(warehouse_name, 'COMPUTE_SERVICE_WH')
    $$;

CREATE OR REPLACE FUNCTION INTERNAL.GET_CREDIT_COST(warehouse number)
    RETURNS NUMBER AS
    $$
    CASE WHEN INTERNAL.IS_SERVERLESS_WAREHOUSE(warehouse) then INTERNAL.GET_SERVERLESS_CREDIT_COST() ELSE INTERNAL.GET_CREDIT_COST() END
    $$;
