
-- Access to the SUNDECK database is given to application_package in deploy.py
-- SHARING.GLOBAL_QUERY_HISTORY is already filtered on SNOWFLAKE_ACCOUNT_LOCATOR = CURRENT_ACCOUNT()
CREATE OR REPLACE VIEW REPORTING.SUNDECK_QUERY_HISTORY
    AS SELECT
        SNOWFLAKE_QUERY_ID,
        SUNDECK_QUERY_ID,
        BROKER_NAME,
        QUERY_TEXT_RECEIVED,
        QUERY_TEXT_FINAL,
        UPDATED_WAREHOUSE_TARGET,
        SUNDECK_STATUS,
        SUNDECK_ERROR_CODE,
        SUNDECK_ERROR_MESSAGE,
        USER_NAME,
        ROLE_NAME,
        TO_TIMESTAMP_LTZ(date_part(EPOCH_MICROSECOND, RAW_START_TIME), 6) as SUNDECK_START_TIME,
        TO_TIMESTAMP_LTZ(date_part(EPOCH_MICROSECOND, RAW_SNOWFLAKE_SUBMISSION_TIME), 6) as SNOWFLAKE_SUBMISSION_TIME,
        TO_TIMESTAMP_LTZ(date_part(EPOCH_MICROSECOND, RAW_SNOWFLAKE_END_TIME), 6) as SNOWFLAKE_END_TIME,
        RAW_ACTIONS['ACTIONS_APPLIED'] as ACTIONS_EXECUTED,
        RAW_ACTIONS['ACTIONS_INPUT']['SCHEMA_ONLY_REQUEST']::BOOLEAN as SCHEMA_ONLY_REQUEST,
        STARTING_WAREHOUSE,
        WORKLOAD_TAG,
        SNOWFLAKE_SESSION_ID
    from SHARING.GLOBAL_QUERY_HISTORY WHERE
        UPPER(SUNDECK_ACCOUNT_ID) = (select UPPER(value) from internal.config where key = 'tenant_id');
